name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: apt-get --yes install pipx llvm-14-tools && pipx install lit && ln -s /usr/lib/llvm-14/bin/FileCheck $HOME/.local/bin/FileCheck
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
